FROM node:19.0-slim AS builder

COPY ./src-vue /src-vue
WORKDIR /src-vue

ENV NODE_ENV=production
RUN npm install; \
    npm run build


FROM caddy:2.6.2

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /src-vue/dist /dist