FROM node:19.0-slim AS builder

COPY ./frontend /frontend

WORKDIR /frontend

RUN npm install; \
    npm run build



FROM caddy:2.6.2

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=builder /frontend/dist /frontend/dist