FROM gradle:7-jdk11 as builder
COPY . /app
WORKDIR /app
RUN gradle --no-daemon installDist

FROM eclipse-temurin:11
COPY --from=builder /app/build/install/wneg /app
ENV LANG C.UTF-8
CMD ["/app/bin/wneg"]